<?php

namespace AppBundle\Repository;

/**
 * MapPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MapPointRepository extends \Doctrine\ORM\EntityRepository
{
}
