# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
#        arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
#services:
#    acme_app.template.my_template:
#        class: Acme\AppBundle\Template\CustomTemplate
#
#    pagerfanta.view.my_template:
#        class: Pagerfanta\View\DefaultView
#        public: false
#        arguments:
#            - "@acme_app.template.my_template"
#        tags: [{ name: pagerfanta.view, alias: my_template }]